version: '3.8'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=users_be
      - POSTGRES_PASSWORD=users_be
      - POSTGRES_DB=users_be_dev

volumes:
  postgres_data: