version: '3.8'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=users_be
      - POSTGRES_PASSWORD=users_be
      - POSTGRES_DB=users_be_dev

  db_test:
    image: postgres:13-alpine
    volumes:
      - pgdata_test:/var/lib/postgresql/_data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433

  test:
    image: python:3.8-alpine
    build:
      context: . 
      dockerfile: DockerfileTest
    command: >
      bash -c "python -m pytest"
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./test.env
    depends_on:
      - db_test


volumes:
  postgres_data:
  pgdata_test: