"""Adds artist_id to User

Revision ID: 2
Revises: 1
Create Date: 2022-05-17 16:46:57.712424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2"
down_revision = "1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("artist_id", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "artist_id")
    # ### end Alembic commands ###
