"""Adds wallet_id

Revision ID: 4
Revises: 3
Create Date: 2022-06-15 15:27:31.173598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4"
down_revision = "3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("wallet_id", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "wallet_id")
    # ### end Alembic commands ###
