name: Test

on: 
  workflow_call:

  push:
    branches-ignore:
      - 'main'
      - 'staging'
  pull_request:
    branches-ignore:
      - 'main'
      - 'staging'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./DockerfileTest
        push: true
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/test:latest

    - name: Run tests
      run: docker-compose -f docker-compose-test.yml run test